[package]
name = "scrapers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tl = "0.7.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
core = { path = "../core" }
